version: '3.4'

services:
  accoliteassessment:
    container_name: banking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80" 
    depends_on: 
       - db
    restart: on-failure
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Pass@123
